### ISSUE TITLE
Potential memory leak in `generate_kmeans_centres`

### ISSUE THREAD

**Issue by jesseli2002** [mhoward3210/ccl#7]
https://github.com/mhoward3210/ccl/blob/8c8c9be029637bf483cf758e90419d061c34657d/C_Version/src/ccl_math.c#L485

If I'm understanding the code right, the early return on convergence causes a memory leak; easiest fix would be to replace it with a `break` statement instead of `return`.

**Comment by VladimirIvan** [comment]
@jesseli2002 You are correct. Lines [484](https://github.com/mhoward3210/ccl/blob/8c8c9be029637bf483cf758e90419d061c34657d/C_Version/src/ccl_math.c#L484) and [485](https://github.com/mhoward3210/ccl/blob/8c8c9be029637bf483cf758e90419d061c34657d/C_Version/src/ccl_math.c#L485) can be both replaced with a `break` statement since `memcpy` happens outside of the loop anyway.

Could you create a pull request for these?
